# Generated by Django 4.0.2 on 2022-03-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=2000)),
                ('title', models.CharField(max_length=200)),
                ('describe', models.TextField(null=True)),
            ],
        ),
    ]
