# Generated by Django 4.0.3 on 2022-03-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0003_comment_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Surname', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=2000)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
