# Generated by Django 4.0.3 on 2022-04-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0005_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='login',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
